export const citationTypes = {
    GET_CITATIONS_START: "GET_CITATIONS_START",
    GET_CITATIONS_SUCCESS: "GET_CITATIONS_SUCCESS",
    GET_CITATIONS_FAIL: "GET_CITATIONS_FAIL",

    CREATE_CITATION_START: "CREATE_CITATION_START",
    CREATE_CITATION_SUCCESS: "CREATE_CITATION_SUCCESS",
    CREATE_CITATION_FAIL: "CREATE_CITATION_FAIL",

    GET_CITATION_BY_ID_START: "GET_CITATION_BY_ID_START",
    GET_CITATION_BY_ID_SUCCESS: "GET_CITATION_BY_ID_SUCCESS",
    GET_CITATION_BY_ID_FAIL: "GET_CITATION_BY_ID_FAIL",

    UPDATE_CITATION_START: "UPDATE_CITATION_START",
    UPDATE_CITATION_SUCCESS: "UPDATE_CITATION_SUCCESS",
    UPDATE_CITATION_FAIL: "UPDATE_CITATION_FAIL",

    DELETE_CITATION_START: "DELETE_CITATION_START",
    DELETE_CITATION_SUCCESS: "DELETE_CITATION_SUCCESS",
    DELETE_CITATION_FAIL: "DELETE_CITATION_FAIL",

    GET_CITATION_START: "GET_CITATION_START",
    GET_CITATION_SUCCESS: "GET_CITATION_SUCCESS",
    GET_CITATION_FAIL: "GET_CITATION_FAIL",


    TOGGLE_CITATION_FAVOURITE_START: "TOGGLE_CITATION_FAVOURITE_START",
    TOGGLE_CITATION_FAVOURITE_SUCCESS: "TOGGLE_CITATION_FAVOURITE_SUCCESS",
    TOGGLE_CITATION_FAVOURITE_FAIL: "TOGGLE_CITATION_FAVOURITE_FAIL",
    

    

}